# Copied from https://svelte.dev/docs/kit/adapter-static#GitHub-Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: 'trunk'

# Considering using a SVELTE_SOURCE_DIR environment variable to store
#   'www-svelte' so that it's easy to change latr. I don't know if that would
#   be idiomatic or strange, however.

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Wasm-Pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # My tests aren't working yet
      # - name: Test Cargo
      #   run: cargo test
      # - name: Test wasm-pack (Chrome)
      #   run: wasm-pack test --headless --chrome
      # - name: Test wasm-pack (Firefox)
      #   run: wasm-pack test --headless --firefox
      - name: Build
        run: |
          wasm-pack build \
          --dev \
          --no-pack \
          --target bundler \
          --out-dir javascript/generated \
          -- --features wasm
  build_svelte:
    needs: build_wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'www-svelte/package.json'
          cache: npm
          cache-dependency-path: 'www-svelte/package-lock.json'
      - name: Install dependencies
        run: npm install
        working-directory: www-svelte
      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        working-directory: www-svelte
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'www-svelte/build/'
  deploy:
    needs: build_svelte
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      # According to ChatGPT, this setting is for deploying to
      #  https://<username>.github.io/
      # url: ''
      # According to ChatGPT, this setting is for deploying to
      #  https://<username>.github.io/<repo-name>/
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
