# Modified from https://svelte.dev/docs/kit/adapter-static#GitHub-Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: 'trunk'

# I repeat this many times, so I figured it'd be good to make it a variable.
# I'm not sure if this is idiomatic or strange.
env:
  SVELTE_SOURCE_DIR: www-svelte

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '$SVELTE_SOURCE_DIR/package.json'
          cache: npm
          cache-dependency-path: '$SVELTE_SOURCE_DIR/package-lock.json'
      - name: Install dependencies
        run: npm install
        working-directory: '$SVELTE_SOURCE_DIR'
      - name: Build
        run: npm run build
        working-directory: '$SVELTE_SOURCE_DIR'
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '$SVELTE_SOURCE_DIR/build/'
  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
